import { createConstants } from '../../../common/utils';

export default createConstants (
  'CHANGE_EVENT_NAME',
  'CHANGE_EVENT_DATE',
  'CHANGE_EVENT_DESCRIPTION',
  'ADD_EVENT_FAILURE',
  'ADD_EVENT_SUCCESS',
  'ADDING_EVENT',
  'CLEAR_MODAL_STATE',
  'GETTING_EVENTS',
  'GET_EVENTS_SUCCESS' ,
  'GET_EVENTS_FAILURE',
  'SET_EVENT',
  'DELETE_EVENT_FAILURE',
  'DELETE_EVENT_SUCCESS',
  'DELETING_EVENT'
);
